### PR TITLE
Update to Xcode 9 & Swift 4 

### PR DESCRIPTION
**Pull request by okitsutakatomo**
This updates the project to the configuration of Xcode 9 and to use Swift 4 and convert Swift4 syntax.

### CODE REVIEW

**Comment by evermeer** [comment]
For now you could use:
`pod 'AsyncSwift', :git => 'https://github.com/okitsutakatomo/Async'`

**Comment by ldiqual** [comment]
@duemunk Would you mind taking a look at this PR and tell us what else can be done to get it merged? It's a bit unsafe for us to rely on third-party branches :/

**Comment by duemunk** [comment]
The branch is failing on CI. Sorry for  it being responding sooner.

**Comment by rolandkakonyi** [comment]
You have to change the `.travis.yml` from:
`osx_image: xcode8`
to
`osx_image: xcode9.1`

Then it should pass.

**Comment by rsaarloos** [comment]
Any update on this one, changes look good

**Comment by vldalx** [comment]
@duemunk  
The brunch is failing on CI because `Xcode 8` does not support `Swift 4`.
You have to change the settings as described above by @rolandkakonyi

Please, merge the PR. Your framework is quite popular.

**Comment by duemunk** [comment]
@vldalx (or anyone really) Feel free to do the change in the `.travis.yml` file to make the PR not fail CI :)

**Comment by vldalx** [comment]
@okitsutakatomo 
Could you update the PR according to the previous comment?

**Comment by rsaarloos** [comment]
I made a new PR for this see #123 (should be successfully pass the checks of the CI)

**Pull request merged**
