### PR TITLE
Allow app extension API only on iOS target

### PR DESCRIPTION
**Pull request by susieyy**
# Why

I had following warning message at compile, when use Async framework with app extension.

> ld: warning: linking against dylib not safe for use in application extensions: /Users/XXXX/src/some/where/Carthage/Build/iOS/Async.framework/Async

# What

Check `Allow app extension API only` on Project > Async iOS Target > General > Deployment Info.

### CODE REVIEW

**Comment by susieyy** [comment]
THX!

**Comment by duemunk** [comment]
Thank *you*!

**Comment by youngsing** [comment]
Hi, I still got this warning message when use Async framework with app extension.
<code>Allow app extension API only</code> unchecked now?

**Comment by toshi0383** [comment]
I guess it regressed in 2.0.1 .
I will check back when I get time.

**Pull request merged**
