### PR TITLE
Update for Xcode 6.3 beta 2

### PR DESCRIPTION
**Pull request by mbarvian**

### CODE REVIEW

**Comment by joslinm** [comment]
I just fixed this myself. Simple and easy shouldn't conflict I would think with older versions @duemunk? how bout merging?

**Comment by duemunk** [comment]
Do you, @joslinm, have any idea why GCD changed it from `UInt` to `Int`? Seems counter intuitiv to me.

**Comment by joslinm** [comment]
I do not :/ I don't understand why either

**Comment by duemunk** [comment]
Do you, @mbarvian, have any idea as to why this change was made by Apple?

**Comment by josephlord** [comment]
I think this is the answer: https://devforums.apple.com/message/1108937#1108937

**Comment by duemunk** [comment]
@josephlord Thanks! It sounds very reasonable :)

**Pull request merged**
